// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_MagicVilla.Data;

#nullable disable

namespace Practice_MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240526024425_VillaNumber")]
    partial class VillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Practice_MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Private Pool, Ocean View",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9343),
                            Details = "A spacious suite with luxurious amenities and a stunning ocean view.",
                            ImageUrl = "https://example.com/luxury-suite.jpg",
                            Name = "Luxury Suite",
                            Occupancy = 4,
                            Rate = 450.0,
                            Sqft = 1200,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Balcony, King Size Bed",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9352),
                            Details = "A deluxe room featuring a king size bed and a private balcony.",
                            ImageUrl = "https://example.com/deluxe-room.jpg",
                            Name = "Deluxe Room",
                            Occupancy = 2,
                            Rate = 300.0,
                            Sqft = 800,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Kitchenette, Two Queen Beds",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9353),
                            Details = "Perfect for families, this room includes a kitchenette and two queen beds.",
                            ImageUrl = "https://example.com/family-room.jpg",
                            Name = "Family Room",
                            Occupancy = 5,
                            Rate = 350.0,
                            Sqft = 1500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Free WiFi, Queen Bed",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9354),
                            Details = "A standard room with all the essentials for a comfortable stay.",
                            ImageUrl = "https://example.com/standard-room.jpg",
                            Name = "Standard Room",
                            Occupancy = 2,
                            Rate = 200.0,
                            Sqft = 600,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Office Area, Complimentary Breakfast",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9355),
                            Details = "An executive suite featuring an office area and complimentary breakfast.",
                            ImageUrl = "https://example.com/executive-suite.jpg",
                            Name = "Executive Suite",
                            Occupancy = 3,
                            Rate = 400.0,
                            Sqft = 1100,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Jacuzzi, Romantic Decor",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9357),
                            Details = "A romantic suite perfect for honeymooners, complete with a jacuzzi.",
                            ImageUrl = "https://example.com/honeymoon-suite.jpg",
                            Name = "Honeymoon Suite",
                            Occupancy = 2,
                            Rate = 500.0,
                            Sqft = 1000,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Private Elevator, Panoramic View",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9358),
                            Details = "The presidential suite offers the ultimate in luxury with a private elevator and panoramic views.",
                            ImageUrl = "https://example.com/presidential-suite.jpg",
                            Name = "Presidential Suite",
                            Occupancy = 4,
                            Rate = 1000.0,
                            Sqft = 2000,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Living Area, Sofa Bed",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9359),
                            Details = "A junior suite with a separate living area and a sofa bed.",
                            ImageUrl = "https://example.com/junior-suite.jpg",
                            Name = "Junior Suite",
                            Occupancy = 3,
                            Rate = 320.0,
                            Sqft = 900,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Single Bed, Free Coffee",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9360),
                            Details = "A cozy single room with a comfortable single bed and free coffee.",
                            ImageUrl = "https://example.com/single-room.jpg",
                            Name = "Single Room",
                            Occupancy = 1,
                            Rate = 150.0,
                            Sqft = 400,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Two Double Beds, Free Parking",
                            CreatedDate = new DateTime(2024, 5, 26, 5, 44, 24, 698, DateTimeKind.Local).AddTicks(9361),
                            Details = "A room with two double beds, ideal for friends traveling together.",
                            ImageUrl = "https://example.com/double-room.jpg",
                            Name = "Double Room",
                            Occupancy = 2,
                            Rate = 220.0,
                            Sqft = 700,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
